load("@rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "product",
    srcs = [
        "handler.go",
        "model.go",
        "store.go",
    ],
    importpath = "lumin.studio/services/api-gateway/internal/product",
    visibility = ["//services/api-gateway:__pkg__"],
    deps = [
        "@com_github_jackc_pgx_v5//:pgx",
    ],
)

go_test(
    name = "product_test",
    srcs = [
        "handler_test.go",
        "model_test.go",
        "store_test.go",
    ],
    embed = [":product"],
)
