apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: lumin-dev
servers: 1
agents: 0
image: docker.io/rancher/k3s:v1.35.5-k3s1
options:
  k3d:
    wait: true
    timeout: 120s
    disableLoadbalancer: false
    disableImageVolume: false
    disableRollback: false
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: false
