package(default_visibility = ["//visibility:public"])

filegroup(
    name = "dev-cluster",
    srcs = ["dev-cluster.sh"],
)

filegroup(
    name = "import-api-image",
    srcs = ["import-api-image.sh"],
)

filegroup(
    name = "import-worker-image",
    srcs = ["import-worker-image.sh"],
)

exports_files(["README.md"])
