apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - meilisearch-ingress.yaml
  - meilisearch-secret.yaml
  - meilisearch-service.yaml
  - meilisearch-statefulset.yaml
  - minio-secret.yaml
  - minio-console-ingress.yaml
  - minio-service.yaml
  - minio-statefulset.yaml
  - minio-buckets-job.yaml
  - nats-deployment.yaml
  - nats-service.yaml
  - postgres-secret.yaml
  - postgres-service.yaml
  - postgres-statefulset.yaml
  - worker-3d-deployment.yaml
