apiVersion: v1
kind: Secret
metadata:
  name: meilisearch
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/component: search
type: Opaque
stringData:
  MEILI_MASTER_KEY: "harness_meilisearch_development_key"
